/** @file
*
*  Copyright (c) Microsoft Corporation. All rights reserved.
*  Copyright 2020 NXP
*
*  This program and the accompanying materials
*  are licensed and made available under the terms and conditions of the BSD License
*  which accompanies this distribution.  The full text of the license may be found at
*  http://opensource.org/licenses/bsd-license.php
*
*  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
*  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
*
**/

#ifndef DISPLAY_MIX_GPR_H_
#define DISPLAY_MIX_GPR_H_

#include <stdint.h>

#if defined(CPU_IMX8MQ)
	#error "DISPLAY_MIX block is not present on iMX8MQ."
#endif

/*
 * Display MIX GPR (uses highest 32KB address of ISI)
 */
#define DISPLAY_MIX_GPR_BASE  0x32E28000
#define DISPLAY_MIX_GPR_SIZE  0x8000

/* Dispmix GPR registers */
/* DISPLAY_MIX_SFT_RSTN_CSR register */
#define DISPLAY_MIX_SFT_RSTN_CSR                        (*((volatile uint32_t *)(DISPLAY_MIX_GPR_BASE + 0x00)))
#if defined(CPU_IMX8MN)
#define DISPLAY_MIX_SFT_EN_BUS_BLK_CLK_RESETN_SHIFT                 8U
#define DISPLAY_MIX_SFT_EN_BUS_BLK_CLK_RESETN_MASK                  (1UL << DISPLAY_MIX_SFT_EN_BUS_BLK_CLK_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_ISI_APB_CLK_RESETN_SHIFT                 7U
#define DISPLAY_MIX_SFT_EN_ISI_APB_CLK_RESETN_MASK                  (1UL << DISPLAY_MIX_SFT_EN_ISI_APB_CLK_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_ISI_PROC_CLK_RESETN_SHIFT                6U
#define DISPLAY_MIX_SFT_EN_ISI_PROC_CLK_RESETN_MASK                 (1UL << DISPLAY_MIX_SFT_EN_ISI_PROC_CLK_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_LCDIF_APB_CLK_RESETN_SHIFT               5U
#define DISPLAY_MIX_SFT_EN_LCDIF_APB_CLK_RESETN_MASK                (1UL << DISPLAY_MIX_SFT_EN_LCDIF_APB_CLK_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_LCDIF_PIXEL_CLK_RESETN_SHIFT             4U
#define DISPLAY_MIX_SFT_EN_LCDIF_PIXEL_CLK_RESETN_MASK              (1UL << DISPLAY_MIX_SFT_EN_LCDIF_PIXEL_CLK_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_MIPI_CSI_ACLK_RESETN_SHIFT               3U
#define DISPLAY_MIX_SFT_EN_MIPI_CSI_ACLK_RESETN_MASK                (1UL << DISPLAY_MIX_SFT_EN_MIPI_CSI_ACLK_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_MIPI_CSI_PCLK_RESETN_SHIFT               2U
#define DISPLAY_MIX_SFT_EN_MIPI_CSI_PCLK_RESETN_MASK                (1UL << DISPLAY_MIX_SFT_EN_MIPI_CSI_PCLK_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_MIPI_DSI_CLKREF_RESETN_SHIFT             1U
#define DISPLAY_MIX_SFT_EN_MIPI_DSI_CLKREF_RESETN_MASK              (1UL << DISPLAY_MIX_SFT_EN_MIPI_DSI_CLKREF_RESETN_SHIFT)
#define DISPLAY_MIX_SFT_EN_MIPI_DSI_PCLK_RESETN_SHIFT               0U
#define DISPLAY_MIX_SFT_EN_MIPI_DSI_PCLK_RESETN_MASK                (1UL << DISPLAY_MIX_SFT_EN_MIPI_DSI_PCLK_RESETN_SHIFT)

#elif defined(CPU_IMX8MM)
#define DISPLAY_MIX_SFT_EN_BUS_RSTN_BLK_SYNC_SFT_EN_SHIFT           (6)
#define DISPLAY_MIX_SFT_EN_BUS_RSTN_BLK_SYNC_SFT_EN_MASK            (1UL << DISPLAY_MIX_SFT_EN_BUS_RSTN_BLK_SYNC_SFT_EN_SHIFT)
#define DISPLAY_MIX_SFT_EN_MIPI_DSI_I_PRESETn_SFT_EN_SHIFT          (5)
#define DISPLAY_MIX_SFT_EN_MIPI_DSI_I_PRESETn_SFT_EN_MASK           (1UL << DISPLAY_MIX_SFT_EN_MIPI_DSI_I_PRESETn_SFT_EN_SHIFT)
#define DISPLAY_MIX_SFT_EN_MIPI_CSI_I_PRESET_SHIFT                  (4)
#define DISPLAY_MIX_SFT_EN_MIPI_CSI_I_PRESET_MASK                   (1UL << DISPLAY_MIX_SFT_EN_MIPI_CSI_I_PRESET_SHIFT)

#define DISPLAY_MIX_SFT_EN_CAMERA_PIXEL_RESET_SHIFT                 (3)
#define DISPLAY_MIX_SFT_EN_CAMERA_PIXEL_RESET_MASK                  (1UL << DISPLAY_MIX_SFT_EN_CAMERA_PIXEL_RESET_SHIFT)

#define DISPLAY_MIX_SFT_EN_CSI_BRIDGE_CSI_HRESET_SHIFT              (2)
#define DISPLAY_MIX_SFT_EN_CSI_BRIDGE_CSI_HRESET_MASK               (1UL << DISPLAY_MIX_SFT_EN_CSI_BRIDGE_CSI_HRESET_SHIFT)

#define DISPLAY_MIX_SFT_EN_CSI_BRIDGE_IPG_HARD_ASYNC_RESET_SHIFT    (1)
#define DISPLAY_MIX_SFT_EN_CSI_BRIDGE_IPG_HARD_ASYNC_RESET_MASK     (1UL << DISPLAY_MIX_SFT_EN_CSI_BRIDGE_IPG_HARD_ASYNC_RESET_SHIFT)

#define DISPLAY_MIX_SFT_EN_CSI_BRIDGE_CHIP_RESET_SHIFT              (0)
#define DISPLAY_MIX_SFT_EN_CSI_BRIDGE_CHIP_RESET_MASK               (1UL << DISPLAY_MIX_SFT_EN_CSI_BRIDGE_CHIP_RESET_SHIFT)

#else
#error Display mix - Unsupported target platform.
#endif

/* DISPLAY_MIX_CLK_EN_CSR register */
#define DISPLAY_MIX_CLK_EN_CSR                          (*((volatile uint32_t *)(DISPLAY_MIX_GPR_BASE + 0x04)))
#if defined(CPU_IMX8MN)
#define DISPLAY_MIX_CLK_EN_BUS_BLK_CLK_SHIFT            8U
#define DISPLAY_MIX_CLK_EN_BUS_BLK_CLK_MASK             (1UL << DISPLAY_MIX_CLK_EN_BUS_BLK_CLK_SHIFT)
#define DISPLAY_MIX_CLK_EN_ISI_APB_CLK_SHIFT            7U
#define DISPLAY_MIX_CLK_EN_ISI_APB_CLK_MASK             (1UL << DISPLAY_MIX_CLK_EN_ISI_APB_CLK_SHIFT)
#define DISPLAY_MIX_CLK_EN_ISI_PROC_CLK_SHIFT           6U
#define DISPLAY_MIX_CLK_EN_ISI_PROC_CLK_MASK            (1UL << DISPLAY_MIX_CLK_EN_ISI_PROC_CLK_SHIFT)
#define DISPLAY_MIX_CLK_EN_LCDIF_APB_CLK_SHIFT          5U
#define DISPLAY_MIX_CLK_EN_LCDIF_APB_CLK_MASK           (1UL << DISPLAY_MIX_CLK_EN_LCDIF_APB_CLK_SHIFT)
#define DISPLAY_MIX_CLK_EN_LCDIF_PIXEL_CLK_SHIFT        4U
#define DISPLAY_MIX_CLK_EN_LCDIF_PIXEL_CLK_MASK         (1UL << DISPLAY_MIX_CLK_EN_LCDIF_PIXEL_CLK_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_SHIFT          3U
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_MASK           (1UL << DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_SHIFT          2U
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_MASK           (1UL << DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_CLKREF_SHIFT        1U
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_CLKREF_MASK         (1UL << DISPLAY_MIX_CLK_EN_MIPI_DSI_CLKREF_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_PCLK_SHIFT          0U
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_PCLK_MASK           (1UL << DISPLAY_MIX_CLK_EN_MIPI_DSI_PCLK_SHIFT)

#elif defined(CPU_IMX8MM)
#define DISPLAY_MIX_CLK_EN_BUS_BLK_CLK_SFT_EN_SHIFT             (12)
#define DISPLAY_MIX_CLK_EN_BUS_BLK_CLK_SFT_EN_MASK              (1UL << DISPLAY_MIX_CLK_EN_BUS_BLK_CLK_SFT_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_CLKREF_SFT_EN_SHIFT         (9)
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_CLKREF_SFT_EN_MASK          (1UL << DISPLAY_MIX_CLK_EN_MIPI_DSI_CLKREF_SFT_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_PCLK_SFT_EN_SHIFT           (8)
#define DISPLAY_MIX_CLK_EN_MIPI_DSI_PCLK_SFT_EN_MASK            (1UL << DISPLAY_MIX_CLK_EN_MIPI_DSI_PCLK_SFT_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_LCDIF_PIXEL_CLK_SFT_EN_SHIFT         (7)
#define DISPLAY_MIX_CLK_EN_LCDIF_PIXEL_CLK_SFT_EN_MASK          (1UL << DISPLAY_MIX_CLK_EN_LCDIF_PIXEL_CLK_SFT_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_LCDIF_APB_CLK_SFT_EN_SHIFT           (6)
#define DISPLAY_MIX_CLK_EN_LCDIF_APB_CLK_SFT_EN_MASK            (1UL << DISPLAY_MIX_CLK_EN_LCDIF_APB_CLK_SFT_EN_SHIFT)

#define DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_EN_SHIFT               (11)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_EN_MASK                (1UL << DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_EN_SHIFT               (10)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_EN_MASK                (1UL << DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_RAW_EN_SHIFT    (5)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_RAW_EN_MASK     (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_RAW_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_EN_SHIFT        (4)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_EN_MASK         (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_EN_SHIFT          (3)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_EN_MASK           (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_MEM_WRAPPER_CLK_EN_SHIFT  (2)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_MEM_WRAPPER_CLK_EN_MASK   (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_MEM_WRAPPER_CLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_SPU_CLK_EN_SHIFT          (1)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_SPU_CLK_EN_MASK           (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_SPU_CLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_CSI_HCLK_EN_SHIFT         (0)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_CSI_HCLK_EN_MASK          (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_CSI_HCLK_EN_SHIFT)

#define DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_EN_SHIFT               (11)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_EN_MASK                (1UL << DISPLAY_MIX_CLK_EN_MIPI_CSI_PCLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_EN_SHIFT               (10)
#define DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_EN_MASK                (1UL << DISPLAY_MIX_CLK_EN_MIPI_CSI_ACLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_RAW_EN_SHIFT    (5)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_RAW_EN_MASK     (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_RAW_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_EN_SHIFT        (4)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_EN_MASK         (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_S_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_EN_SHIFT          (3)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_EN_MASK           (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_IPG_CLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_MEM_WRAPPER_CLK_EN_SHIFT  (2)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_MEM_WRAPPER_CLK_EN_MASK   (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_MEM_WRAPPER_CLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_SPU_CLK_EN_SHIFT          (1)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_SPU_CLK_EN_MASK           (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_SPU_CLK_EN_SHIFT)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_CSI_HCLK_EN_SHIFT         (0)
#define DISPLAY_MIX_CLK_EN_CSI_BRIDGE_CSI_HCLK_EN_MASK          (1UL << DISPLAY_MIX_CLK_EN_CSI_BRIDGE_CSI_HCLK_EN_SHIFT)

#else
#error Display mix - Unsupported target platform.
#endif

/* GPR_MIPI_RESET_DIV register */
#define DISPLAY_MIX_GPR_MIPI_RESET_DIV                  (*((volatile uint32_t *)(DISPLAY_MIX_GPR_BASE + 0x08)))

#define DISPLAY_MIX_GPR_MIPI_S_RESETN_SHIFT             16U
#define DISPLAY_MIX_GPR_MIPI_S_RESETN_MASK              (1UL << DISPLAY_MIX_GPR_MIPI_S_RESETN_SHIFT)
#define DISPLAY_MIX_GPR_MIPI_M_RESETN_SHIFT             17U
#define DISPLAY_MIX_GPR_MIPI_M_RESETN_MASK              (1UL << DISPLAY_MIX_GPR_MIPI_M_RESETN_SHIFT)

/* End of DISPLAY_MIX_GPR_H_ */
#endif
